
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include <type_traits>

#include "GameData/UGameDataDocument.h"
#include "GameData/FLocalizedText.h"
#include "GameData/ULanguageSwitcher.h"
#include "GameData/EGameDataFormat.h"
#include "GameData/UGameDataBase.h"
#include "GameData/FGameDataLoadOptions.h"
#include "GameData/FGameDataDocumentIdConvert.h"
#include "GameData/Formatters/FGameDataReaderFactory.h"
#include "GameData/Formatters/IGameDataReader.h"
#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2
#include "GameData/Formulas/FFormulaTypeResolver.h"
#include "GameData/Formulas/UFormulaExpressionDefaultGlobal.h"
#include "UObject/ReflectedTypeAccessors.h"
#include "UObject/Class.h"
#endif
#include "Engine/Engine.h"
#include "UObject/Object.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonTypes.h"
#include "Serialization/Archive.h"
#include "Runtime/Launch/Resources/Version.h"
#include "Misc/EngineVersionComparison.h"
#include "UGdReleaseAProjectSettings.h"
#include "UGdReleaseA.generated.h"

DECLARE_LOG_CATEGORY_EXTERN(LogUGdReleaseA, Log, All);

/**
  * Main class used to access game data.
  */
UCLASS(BlueprintType)
class GDRELEASEA_API UGdReleaseA : public UGameDataBase
{
	GENERATED_BODY()

public:
	inline static const FString GeneratorName = TEXT("Charon");
	inline static const FString GeneratorVersion = TEXT("2026.3.4.0");

private:

	UPROPERTY()
	TMap<FString,UGdReleaseAProjectSettings*> AllProjectSettingsList;
	UPROPERTY()
	TMap<FString,UGdReleaseAProjectSettings*> ProjectSettingsList;

	TSharedPtr<TArray<UGameDataDocument*>> RootDocuments;
	TSharedPtr<TArray<UGameDataDocument*>> AllDocuments;
	TSharedPtr<TMap<FString, UObject*>> NameLookupDuringLoading;

	UPROPERTY()
	ULanguageSwitcher* LanguageSwitcher;

public:
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 ChangeNumber;

	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString RevisionHash;

	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString GameDataVersion;

	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TArray<FString> SupportedLanguages;

	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	UGdReleaseAProjectSettings* ProjectSettings;

#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2
	static TSharedRef<FFormulaTypeResolver> GetSharedFormulaTypeResolver();
#endif

	virtual bool TryLoad(FArchive* const GameDataStream, EGameDataFormat Format) override;
	bool TryLoad(FArchive* const GameDataStream, FGameDataLoadOptions Options);

	const TArray<UGameDataDocument*>& GetAllDocuments() const;
	const TArray<UGameDataDocument*>& GetRootDocuments() const;

	virtual UGameDataDocument* FindGameDataDocumentById(const FString& SchemaNameOrId, const FString& DocumentId) override;
	virtual UClass* FindDocumentSchemaClass(const FString& SchemaNameOrId) override;
	virtual void GetDocumentIds(const FString& SchemaNameOrId, TArray<FString>& OutAllIds) override;
	virtual void GetDocumentSchemaNames(TArray<FString>& OutAllSchemaNames) override;
	virtual void SetSupportedLanguages(const TArray<FString>& LanguageIds) override;

#if defined(CHARON_PLUGIN_MAJOR_VERSION) && defined(CHARON_PLUGIN_MINOR_VERSION) && \
    (CHARON_PLUGIN_MAJOR_VERSION > 2025 || (CHARON_PLUGIN_MAJOR_VERSION == 2025 && CHARON_PLUGIN_MINOR_VERSION >= 3))
	virtual FStringView GetRevisionHash() override
	{
		return this->RevisionHash;
	}
#endif

	UFUNCTION(BlueprintCallable)
	void SetLanguage(
		FString LanguageId,
		FString FallbackLanguageId = TEXT("en-US"),
		ELocalizedTextFallbackOption FallbackOption = ELocalizedTextFallbackOption::OnNull)
	{
		if (LanguageSwitcher == nullptr)
		{
			return;
		}

		LanguageSwitcher->CurrentLanguageId = LanguageId;
		LanguageSwitcher->FallbackLanguageId = FallbackLanguageId;
		LanguageSwitcher->FallbackOption = FallbackOption;
	}

private:
	void Empty();
	void UpdateProjectSettings();
	void UpdateSettings();
	void ParseLanguageList(const FString& InLanguages, TArray<FString>& OutLanguageList);

	template <typename IdType, typename DocumentType>
	DocumentType* GetOne(const TMap<IdType, DocumentType*>& Documents) const;
	template <typename IdType, typename DocumentType>
	void ToMapById(TMap<IdType, DocumentType*>& DocumentsById, TArray<DocumentType*>& Documents);
	TSharedRef<IGameDataReader> CreateReader(FArchive* const GameDataStream, const FGameDataLoadOptions& Options);

	bool ReadGameData(const TSharedRef<IGameDataReader>& Reader);
	bool ReadDocument
	(
		const TSharedRef<IGameDataReader>& Reader,
		UGdReleaseAProjectSettings*& Document,
		UObject* Outer,
		TArray<FString>& GameDataPath,
		bool NextToken = true
	);
	template <typename IdType, typename DocumentType>
	bool ReadDocumentCollection
	(
		const TSharedRef<IGameDataReader>& Reader,
		TMap<IdType,DocumentType*>& Collection,
		int32 Capacity,
		UObject* Outer,
		TArray<FString>& GameDataPath,
		bool NextToken = true
	);
	bool ReadLocalizedText
	(
		const TSharedRef<IGameDataReader>& Reader,
		FLocalizedText& LocalizedText,
		TArray<FString>& GameDataPath,
		bool NextToken = true
	);

	template <typename DocumentReferenceType>
	bool ReadDocumentReferenceCollection
	(
		const TSharedRef<IGameDataReader>& Reader,
		TArray<DocumentReferenceType>& Collection,
		const FString& SchemaIdOrName,
		TArray<FString>& GameDataPath,
		bool NextToken = true
	);

	bool ReadDocumentReference
	(
		const TSharedRef<IGameDataReader>& Reader,
		FGameDataDocumentReference& DocumentReference,
		const FString& SchemaIdOrName,
		TArray<FString>& GameDataPath,
		bool NextToken = true
	);

	template <typename FormulaType>
	bool ReadFormula
	(
		const TSharedRef<IGameDataReader>& Reader,
		FormulaType*& Formula,
		UObject* Outer,
		TArray<FString>& GameDataPath,
		bool NextToken = true
	);

	FString CombineGameDataPath(const TArray<FString>& GameDataPath);
	TSharedPtr<FJsonObject> MergeGameData(const TSharedPtr<FJsonObject>& GameDataDocument, const TSharedPtr<FJsonObject>& PatchDocument);
	template <typename DocumentType>
	TSharedPtr<FJsonValue> MergeDocumentCollection(TSharedRef<FJsonValue> OriginalCollection, TSharedRef<FJsonValue> ModifiedCollection, bool PurgeRest);
	template <typename DocumentType>
	TSharedPtr<FJsonValue> MergeDocument(TSharedRef<FJsonValue> OriginalDocument, TSharedRef<FJsonValue> ModifiedDocument);
	typedef TOptional<TFunction<TSharedPtr<FJsonValue>(TSharedRef<FJsonValue>, TSharedRef<FJsonValue>)>> OptionalMergeValueFunc;
	void MergePropertyDocumentValue(TSharedRef<FJsonObject> MergedDocument, TSharedRef<FJsonObject> OriginalDocument, TSharedRef<FJsonObject> ModifiedDocument, const FString PropertyName, OptionalMergeValueFunc MergeFn = OptionalMergeValueFunc());
	void MergePropertyLanguagesValue(TSharedRef<FJsonObject> MergedDocument, TSharedRef<FJsonObject> OriginalDocument, TSharedRef<FJsonObject> ModifiedDocument, const FString PropertyName);
	void MergePropertyValue(TSharedRef<FJsonObject> MergedDocument, TSharedRef<FJsonObject> OriginalDocument, TSharedRef<FJsonObject> ModifiedDocument, const FString PropertyName, OptionalMergeValueFunc MergeFn = OptionalMergeValueFunc());
	TSharedRef<FJsonValue> MergeLocalizedText(TSharedRef<FJsonValue> OriginalLocalizedText, TSharedRef<FJsonValue> ModifiedLocalizedText);
	template <typename KeyType>
	TSharedRef<TArray<KeyType>> MergeKeys(const TMap<KeyType, TSharedPtr<FJsonValue>>& Collection1, const TMap<KeyType, TSharedPtr<FJsonValue>>& Collection2);
public:
	void ResolveAllReferences();
	void FindAllDocuments();

	class FVisitor
	{
	public:
		virtual ~FVisitor() = default;

		/*
         * Base visit method. Called to dispatch each document.
		 */
		virtual void Visit(UGameDataDocument* Document);

		// visit methods
		virtual void Visit(UGdReleaseAProjectSettings& Document);
	};

	void ApplyVisitor(FVisitor& Visitor) const;

	class FFindingVisitor : public FVisitor
	{
	public:
		// collected documents
		TArray<UGdReleaseAProjectSettings*> ProjectSettings = TArray<UGdReleaseAProjectSettings*>();

		// visit methods
		virtual void Visit(UGdReleaseAProjectSettings& Document) override;
	};

private:
	class FDereferencingVisitor : public FVisitor
	{
		// visit methods
		virtual void Visit(UGdReleaseAProjectSettings& Document) override;
	};

	class FLanguagesUpdateVisitor : public FVisitor
	{
	private:
		const TArray<FString> LanguageIds;

	public:
		FLanguagesUpdateVisitor(const TArray<FString>& LanguageIds);

		// visit methods
		virtual void Visit(UGdReleaseAProjectSettings& Document) override;
		void RemoveExtraKeys(TMap<FString, FText>& TextByLanguageId);
	};
};
