
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "GameData/EDocumentReferenceGetResult.h"
#include "UGdReleaseAProjectSettings.h"

#include "UGdReleaseAFunctionLibrary.generated.h"

/**
  * Extension functions for generate UGdReleaseA class.
  */
UCLASS()
class GDRELEASEA_API UGdReleaseAFunctionLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

	/*
	 * Get UGdReleaseAProjectSettings referenced in specified DocumentReference.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static UGdReleaseAProjectSettings* GetGdReleaseAProjectSettings(FGameDataDocumentReference DocumentReference, EDocumentReferenceGetResult& Branches)
	{
		UGdReleaseAProjectSettings* Document = Cast<UGdReleaseAProjectSettings>(DocumentReference.GetReferencedDocument());
		if (Document == nullptr)
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
		return Document;
	}
};
