
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

#include "UGdReleaseA.h"
#include "UGdReleaseAProjectSettings.h"

DEFINE_LOG_CATEGORY(LogUGdReleaseA);

#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2
TSharedRef<FFormulaTypeResolver> UGdReleaseA::GetSharedFormulaTypeResolver()
{
	static TSharedRef<FFormulaTypeResolver> SharedFormulaTypeResolver = MakeShared<FFormulaTypeResolver>(nullptr, TArray<UObject*> {
		UGdReleaseAProjectSettings::StaticClass(),
	});

	return SharedFormulaTypeResolver;
}
#endif

void UGdReleaseA::Empty()
{
	if (LanguageSwitcher)
	{
		LanguageSwitcher->CurrentLanguageId = TEXT("en-US");
		LanguageSwitcher->FallbackLanguageId = TEXT("en-US");
		LanguageSwitcher->PrimaryLanguageId = TEXT("en-US");
	}

	RootDocuments = nullptr;
	AllDocuments = nullptr;

	ChangeNumber = 0;
	RevisionHash.Empty();

	ProjectSettings = nullptr;
	AllProjectSettingsList.Reset();
	ProjectSettingsList.Reset();

	SupportedLanguages.Reset();

#if defined(GDRELEASEA_CLEAN_GAME_DATA_LOAD) && GDRELEASEA_CLEAN_GAME_DATA_LOAD
	// Array to temporarily hold objects to be destroyed.
    // We cannot destroy them while iterating through the collection.
    TArray<UObject*> ChildrenToDestroy;

    ForEachObjectWithOuter(this, [&](UObject* Child)
    {
		// skip already deleted or non-document objects
        if (Child->HasAnyFlags(EObjectFlags::RF_MirroredGarbage) ||
			!Cast<UGameDataDocument>(Child))
        {
            return;
        }
		ChildrenToDestroy.Add(Child);
    },
    /* bIncludeNested */ false);

	for (UObject* Child : ChildrenToDestroy)
    {
        Child->MarkAsGarbage();
        Child->Rename(nullptr, GetTransientPackage(), REN_DontCreateRedirectors | REN_NonTransactional | REN_ForceNoResetLoaders);
    }
#endif
}

bool UGdReleaseA::TryLoad(FArchive* const GameDataStream, EGameDataFormat Format)
{
	auto Options = FGameDataLoadOptions();
	Options.Format = Format;
	return TryLoad(GameDataStream, Options);
}
bool UGdReleaseA::TryLoad(FArchive* const GameDataStream, FGameDataLoadOptions Options)
{
	Empty(); // Reset current state

	SupportedLanguages.Add(TEXT("en-US"));

	if (LanguageSwitcher == nullptr)
	{
		LanguageSwitcher = NewObject<ULanguageSwitcher>(this);
	}
	LanguageSwitcher->CurrentLanguageId = TEXT("en-US");
	LanguageSwitcher->FallbackLanguageId = TEXT("en-US");
	LanguageSwitcher->PrimaryLanguageId = TEXT("en-US");

	auto GameDataReader = CreateReader(GameDataStream, Options);
	GameDataReader->ReadNext(); // initialize reader and move to first token

	if (Options.Patches.Num() > 0)
	{
		TSharedPtr<FJsonObject> GameDataDocument = nullptr;
		if (!GameDataReader->ReadObject(GameDataDocument, /* NextToken */  false))
		{
			GameDataDocument = nullptr;
			UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read Game Data from file. Probably file format is wrong or file is broken."));
			return false;
		}
		for (const auto GameDataPatchStream : Options.Patches)
		{
			const auto GameDataPatchReader = CreateReader(GameDataPatchStream, Options);
			GameDataPatchReader->ReadNext(); // initialize reader and move to first token

			TSharedPtr<FJsonObject> GameDataPatchDocument;
			if (!GameDataPatchReader->ReadObject(GameDataPatchDocument, /* NextToken */  false))
			{
				GameDataPatchDocument = nullptr;
				UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read Game Data patch from file. Probably file format is wrong or file is broken."));
				return false;
			}

			GameDataDocument = MergeGameData(GameDataDocument, GameDataPatchDocument);
		}

		if (GameDataDocument == nullptr)
		{
			UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to apply Game Data patch."));
			return false;
		}

		GameDataReader = FGameDataReaderFactory::CreateJsonObjectReader(GameDataDocument);
		GameDataReader->ReadNext(); // initialize reader and move to first token
	}

	if (!ReadGameData(GameDataReader))
	{
		UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to parse Game Data from file."));
		return false;
	}

	FindAllDocuments();
	UpdateProjectSettings();
	UpdateSettings();

	return true;
}

void UGdReleaseA::UpdateProjectSettings()
{
	const auto _ProjectSettings = GetOne(this->ProjectSettingsList);
	if (_ProjectSettings == nullptr)
	{
		return;
	}
	GameDataVersion = _ProjectSettings->Version;

	const auto _ProjectSettingsLanguages = _ProjectSettings->Languages;
	if (_ProjectSettingsLanguages.IsEmpty())
	{
		return;
	}

	SupportedLanguages.Empty();

	ParseLanguageList(_ProjectSettingsLanguages, SupportedLanguages);

	const auto _ProjectSettingsPrimaryLanguage = _ProjectSettings->PrimaryLanguage;
	if (!_ProjectSettingsPrimaryLanguage.IsEmpty())
	{
		LanguageSwitcher->PrimaryLanguageId = _ProjectSettingsPrimaryLanguage;
	}
	else if (SupportedLanguages.Num() > 0)
	{
		LanguageSwitcher->PrimaryLanguageId = SupportedLanguages[0];
	}
	else
	{
		LanguageSwitcher->PrimaryLanguageId = TEXT("en-US");
	}

	LanguageSwitcher->CurrentLanguageId = LanguageSwitcher->FallbackLanguageId = LanguageSwitcher->PrimaryLanguageId;
	if (!SupportedLanguages.Contains(LanguageSwitcher->PrimaryLanguageId))
	{
		SupportedLanguages.Add(LanguageSwitcher->PrimaryLanguageId);
	}
	SupportedLanguages.Sort();
}

void UGdReleaseA::ParseLanguageList(const FString& InLanguages, TArray<FString>& OutLanguageList)
{
	auto Languages = FString(InLanguages);
	Languages.ReplaceCharInline(TEXT(','), TEXT(';'));
	Languages.ReplaceCharInline(TEXT('|'), TEXT(';'));
	Languages.ReplaceCharInline(TEXT(' '), TEXT(';'));
	Languages.ParseIntoArray(OutLanguageList, TEXT(";"), /* inCullEmpty */ true);
}

void UGdReleaseA::UpdateSettings()
{
	this->ProjectSettings = GetOne(this->ProjectSettingsList);
}

const TArray<UGameDataDocument*>& UGdReleaseA::GetAllDocuments() const
{
	if (AllDocuments != nullptr)
	{
		return AllDocuments.ToSharedRef().Get();
	}

	const auto FoundDocuments = MakeShared<TArray<UGameDataDocument*>>();
	for (const auto DocumentById : AllProjectSettingsList)
	{
		FoundDocuments->Add(DocumentById.Value);
	}
	const_cast<UGdReleaseA*>(this)->AllDocuments = FoundDocuments;
	return FoundDocuments.Get();
}

const TArray<UGameDataDocument*>& UGdReleaseA::GetRootDocuments() const
{
	if (RootDocuments != nullptr)
	{
		return RootDocuments.ToSharedRef().Get();
	}

	const auto FoundDocuments = MakeShared<TArray<UGameDataDocument*>>();
	for (const auto DocumentById : ProjectSettingsList)
	{
		FoundDocuments->Add(DocumentById.Value);
	}
	const_cast<UGdReleaseA*>(this)->RootDocuments = FoundDocuments;
	return FoundDocuments.Get();
}

template <typename IdType, typename DocumentType>
DocumentType* UGdReleaseA::GetOne(const TMap<IdType, DocumentType*>& Documents) const
{
	if (Documents.Num() == 1)
	{
        auto Iterator = Documents.CreateConstIterator();
        return Iterator->Value;
	}
	return nullptr;
}

template <typename IdType, typename DocumentType>
void UGdReleaseA::ToMapById(TMap<IdType, DocumentType*>& DocumentsById, TArray<DocumentType*>& Documents)
{
	for (auto Document : Documents)
	{
		DocumentsById.FindOrAdd(Document->Id, Document);
	}
}

UGameDataDocument* UGdReleaseA::FindGameDataDocumentById(const FString& SchemaNameOrId, const FString& DocumentId)
{
	if (SchemaNameOrId.IsEmpty() || DocumentId.IsEmpty())
	{
		return nullptr;
	}
	else if (SchemaNameOrId == TEXT("ProjectSettings") || SchemaNameOrId == TEXT("55a4f32faca22e191098f3d9"))
	{
		FString Id;
		FGameDataDocumentIdConvert::ConvertToType(DocumentId, Id);
		const auto FoundDocument = this->AllProjectSettingsList.Find(Id);
		if (FoundDocument != nullptr)
		{
			return *FoundDocument;
		}
	}
	return nullptr;
}

UClass* UGdReleaseA::FindDocumentSchemaClass(const FString& SchemaNameOrId)
{
	if (SchemaNameOrId.IsEmpty())
	{
		return nullptr;
	}
	else if (SchemaNameOrId == TEXT("ProjectSettings") || SchemaNameOrId == TEXT("55a4f32faca22e191098f3d9"))
	{
		return UGdReleaseAProjectSettings::StaticClass();
	}
	return nullptr;
}

void UGdReleaseA::GetDocumentIds(const FString& SchemaNameOrId, TArray<FString>& AllIds)
{
	if (SchemaNameOrId.IsEmpty())
	{
		return;
	}
	else if (SchemaNameOrId == TEXT("ProjectSettings") || SchemaNameOrId == TEXT("55a4f32faca22e191098f3d9"))
	{
		for (auto DocumentById : AllProjectSettingsList)
		{
			FString IdString;
			FGameDataDocumentIdConvert::ConvertToString(DocumentById.Key, IdString);
			AllIds.Add(IdString);
		}
	}
}

void UGdReleaseA::GetDocumentSchemaNames(TArray<FString>& AllSchemaNames)
{
	AllSchemaNames.Add(TEXT("ProjectSettings"));
}

void UGdReleaseA::SetSupportedLanguages(const TArray<FString>& LanguageIds)
{
	auto LanguagesUpdateVisitor = UGdReleaseA::FLanguagesUpdateVisitor(LanguageIds);
	ApplyVisitor(LanguagesUpdateVisitor);
}


TSharedRef<IGameDataReader> UGdReleaseA::CreateReader(FArchive* const GameDataStream, const FGameDataLoadOptions& Options)
{
	switch (Options.Format)
	{
	case EGameDataFormat::Json:
		return FGameDataReaderFactory::CreateJsonReader(GameDataStream);
	case EGameDataFormat::MessagePack:
		return FGameDataReaderFactory::CreateMessagePackReader(GameDataStream);
	default:
		UE_LOG(LogUGdReleaseA, Error, TEXT("Unknown game data format specified in FGameDataLoadOptions. Fallback to JSON formatter."));
		return FGameDataReaderFactory::CreateJsonReader(GameDataStream);
	}
}

#if UE_VERSION_NEWER_THAN(5, 4, -1)
static constexpr EObjectFlags UGdReleaseA_GARBAGE_FLAG = static_cast<EObjectFlags>(0x40000000); /* EObjectFlags::RF_MirroredGarbage */
#else
static constexpr EObjectFlags UGdReleaseA_GARBAGE_FLAG = static_cast<EObjectFlags>(0x40000000); /* EObjectFlags::RF_Garbage */

#endif

static UObject* UGdReleaseA_FindDocumentByUniqueName(const FString& ObjectName, TSharedPtr<TMap<FString, UObject*>> DocumentsById)
{
	if (!DocumentsById)
	{
		return nullptr;
	}

	const UObject* const* ConstFoundObject = DocumentsById->Find(ObjectName);
	if (!ConstFoundObject)
	{
		return nullptr;
	}

	UObject* FoundObject = const_cast<UObject*>(*ConstFoundObject);
	if (FoundObject->HasAnyFlags(UGdReleaseA_GARBAGE_FLAG))
	{
		return nullptr; // object has been marked for deletion
	}
	return FoundObject;
}
static void UGdReleaseA_FillDocumentByUniqueNameMap(UObject* Outer, TSharedPtr<TMap<FString, UObject*>>& DocumentsById)
{
	if (!Outer) {
		UE_LOG(LogUGdReleaseA, Error, TEXT("Can't fill documents by unique name map for `null` Outer."));
		return;
	}

	if (!DocumentsById)
	{
		DocumentsById = MakeShared<TMap<FString, UObject*>>();
	}
	else
	{
		DocumentsById->Reset();
	}

	// Iterate through all objects with this Outer (including nested)
	ForEachObjectWithOuter(Outer, [DocumentsById](UObject* Child)
	{
		// skip already deleted or non-document objects
		if (Child->HasAnyFlags(UGdReleaseA_GARBAGE_FLAG) ||
			!Cast<UGameDataDocument>(Child))
		{
			return;
		}

		FString ObjectName = Child->GetName();
		if (DocumentsById->Contains(ObjectName))
		{
			UE_LOG(LogUGdReleaseA, Warning, TEXT("Duplicate object name found while filling unique document names map: %s"), *ObjectName);
			return;
		}
		DocumentsById->Add(ObjectName, Child);
	},
#if UE_VERSION_NEWER_THAN(5, 8, -1)
	EGetObjectsFlags::IncludeNestedObjects
#else
	/* bIncludeNested */ true
#endif
	);
}
static void UGdReleaseA_ClearDocumentByUniqueNameMap(TSharedPtr<TMap<FString, UObject*>> DocumentsById)
{
	if (!DocumentsById)
	{
		return;
	}
	DocumentsById->Reset();
}

template <typename DocumentType>
static FString UGdReleaseA_MakeUniqueDocumentName(DocumentType* Document)
{
	if (!Document) {
		UE_LOG(LogUGdReleaseA, Error, TEXT("Can't make unique name for `null` document."));
		return FString();
	}

	FString DocumentUniqueName;
	FGameDataDocumentIdConvert::ConvertToString(Document->Id, DocumentUniqueName);
	DocumentUniqueName.InsertAt(0, TEXT("_"));
	DocumentUniqueName.InsertAt(0, DocumentType::StaticClass()->GetName());
	return DocumentUniqueName;
}

static UObject* UGdReleaseA_ResetDocumentToDefaultState(UObject* Document)
{
	if (!Document)
	{
		return nullptr;
	}

	UObject* DefaultObj = Document->GetClass()->GetDefaultObject();
	// Copy all UPROPERTY values from the default object to 'Document'
    UEngine::CopyPropertiesForUnrelatedObjects(DefaultObj, Document);

	return Document;
}

static void UGdReleaseA_TryRenameDocument(UObject* Document, const TCHAR* NewName)
{
	if (!Document) {
		UE_LOG(LogUGdReleaseA, Error, TEXT("Can't rename `null` document."));
		return;
	}

	if (Document->Rename(NewName, nullptr, REN_NonTransactional | REN_DoNotDirty | REN_DontCreateRedirectors | REN_Test))
	{
		Document->Rename(NewName, nullptr, REN_NonTransactional | REN_DoNotDirty | REN_DontCreateRedirectors);
	}
	else
	{
		// in case of collision we generate unique name
		Document->Rename(*MakeUniqueObjectName(Document->GetOuter(), Document->GetClass(), Document->GetFName()).ToString(), nullptr, REN_NonTransactional | REN_DoNotDirty | REN_DontCreateRedirectors);
	}
}

static void UGdReleaseA_TryDeleteDocument(UObject* Document)
{
	if (!Document) {
		UE_LOG(LogUGdReleaseA, Error, TEXT("Can't delete `null` document."));
		return;
	}

	Document->Rename(nullptr, GetTransientPackage(), REN_DontCreateRedirectors | REN_NonTransactional |
#if UE_VERSION_NEWER_THAN(5, 8, -1)
		REN_AllowPackageLinkerMismatch
#else
		REN_ForceNoResetLoaders
#endif
	);
}

static void UGdReleaseA_MarkChildDocumentsForDeletion(UObject* Document)
{
	if (!Document) {
		UE_LOG(LogUGdReleaseA, Error, TEXT("Can't mark as orphand children for deletion for `null` document."));
		return;
	}

	Document->ClearFlags(EObjectFlags::RF_TagGarbageTemp);

	ForEachObjectWithOuter(Document, [&](UObject* Child)
	{
		if (!Cast<UGameDataDocument>(Child))
		{
			return;
		}
		Child->SetFlags(EObjectFlags::RF_TagGarbageTemp);
	},
#if UE_VERSION_NEWER_THAN(5, 8, -1)
	EGetObjectsFlags::IncludeNestedObjects
#else
	/* bIncludeNested */ true
#endif
	);
}

static void UGdReleaseA_SweepMarkedChildDocuments(UObject* Document)
{
	if (!Document) {
		UE_LOG(LogUGdReleaseA, Error, TEXT("Can't sweep orphained children for `null` document."));
		return;
	}

	TArray<UObject*> ChildrenToDestroy;
	ForEachObjectWithOuter(Document, [&](UObject* Child)
	{
		// skip already deleted or non-document objects
		if (Child->HasAnyFlags(UGdReleaseA_GARBAGE_FLAG) ||
			!Cast<UGameDataDocument>(Child) ||
			!Child->HasAnyFlags(EObjectFlags::RF_TagGarbageTemp))
		{
			return;
		}
		Child->ClearFlags(EObjectFlags::RF_TagGarbageTemp);
		ChildrenToDestroy.Add(Child);
	},
#if UE_VERSION_NEWER_THAN(5, 8, -1)
	EGetObjectsFlags::IncludeNestedObjects
#else
	/* bIncludeNested */ true
#endif
	);

	for (UObject* Child : ChildrenToDestroy)
	{
		Child->MarkAsGarbage();
		Child->Rename(nullptr, GetTransientPackage(), REN_DontCreateRedirectors | REN_NonTransactional |
#if UE_VERSION_NEWER_THAN(5, 8, -1)
		REN_AllowPackageLinkerMismatch
#else
		REN_ForceNoResetLoaders
#endif
		);
	}
}

bool UGdReleaseA::ReadGameData(const TSharedRef<IGameDataReader>& Reader)
{
	auto GameDataPath = TArray<FString>();
	GameDataPath.Add(TEXT(""));

	if (!Reader->ReadObjectBegin())
	{
		UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
		return false;
	}

	UGdReleaseA_FillDocumentByUniqueNameMap(this, this->NameLookupDuringLoading);
	UGdReleaseA_MarkChildDocumentsForDeletion(this);

	while (Reader->GetNotation() != EJsonNotation::ObjectEnd)
	{
		if (Reader->IsError())
		{
			UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
			return false;
		}

		auto MemberName = Reader->ReadMember();
		if (MemberName == TEXT("ChangeNumber"))
		{
			Reader->ReadValue(ChangeNumber);
			Reader->ReadNext();
		}
		else if (MemberName == TEXT("RevisionHash"))
		{
			Reader->ReadValue(RevisionHash);
			Reader->ReadNext();
		}
		else if (MemberName == TEXT("Collections"))
		{
			GameDataPath.Add(TEXT("Collections"));
			Reader->ReadObjectBegin();
			while (Reader->GetNotation() != EJsonNotation::ObjectEnd)
			{
				if (Reader->IsError())
				{
					UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
					return false;
				}

				auto CollectionName = Reader->ReadMember();
				GameDataPath.Add(CollectionName);
				switch (CollectionName.Len())
				{
					case 15:
						if (CollectionName.IsEmpty())
						{
							Reader->SkipAny();
						}
						else if (CollectionName == TEXT("55a4f32faca22e191098f3d9") || CollectionName == TEXT("ProjectSettings"))
						{
							GameDataPath.Add(TEXT("ProjectSettings"));
							if (!ReadDocumentCollection(Reader, this->ProjectSettingsList, 1, this, GameDataPath))
							{
								UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read '%s' document collection. Path: %s."), TEXT("ProjectSettings"), *CombineGameDataPath(GameDataPath));
								return false;
							}
							GameDataPath.Pop();
						}
						else
						{
							Reader->SkipAny();
						}
						break;
					default:
						Reader->SkipAny();
						break;
				}
			}
			Reader->ReadObjectEnd();
			GameDataPath.Pop();
			break;
		}
		else
		{
			Reader->SkipAny();
		}
	}
	Reader->ReadObjectEnd();
	GameDataPath.Pop();

	if (Reader->IsError())
	{
		UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
		return false;
	}

	UGdReleaseA_ClearDocumentByUniqueNameMap(this->NameLookupDuringLoading);
	UGdReleaseA_SweepMarkedChildDocuments(this);

	return true;
}

bool UGdReleaseA::ReadDocument
(
	const TSharedRef<IGameDataReader>& Reader,
	UGdReleaseAProjectSettings*& Document,
	UObject* Outer,
	TArray<FString>& GameDataPath,
	bool NextToken
)
{
	Document = NewObject<UGdReleaseAProjectSettings>(Outer, UGdReleaseAProjectSettings::StaticClass(), NAME_None, EObjectFlags::RF_NoFlags);
	Outer = Document;

	Reader->ReadObjectBegin();
	while (Reader->GetNotation() != EJsonNotation::ObjectEnd)
	{
		if (Reader->IsError())
		{
			UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
			return false;
		}

		auto PropertyName = Reader->ReadMember();
		bool bReadSuccess;
		GameDataPath.Add(PropertyName);
		if (PropertyName.IsEmpty())
		{
			Reader->SkipAny();
		}
		else if (PropertyName == TEXT("Id"))
		{
			if (Reader->IsNull())
			{
				UE_LOG(LogUGdReleaseA, Error, TEXT("Unexpected null value for property '%s' of document. Path: %s."), TEXT("ProjectSettings.Id"), *CombineGameDataPath(GameDataPath));
				return false;
			}
			bReadSuccess = Reader->ReadValue(Document->Id) && Reader->ReadNext();
			if (!bReadSuccess)
			{
				UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read value for property '%s' of document. Path: %s."), TEXT("ProjectSettings.Id"), *CombineGameDataPath(GameDataPath));
				return false;
			}
			FString NewName = UGdReleaseA_MakeUniqueDocumentName(Document);
			UObject* ExistingObject = UGdReleaseA_FindDocumentByUniqueName(NewName, this->NameLookupDuringLoading);
			UGdReleaseAProjectSettings* ExistingDocument = Cast<UGdReleaseAProjectSettings>(ExistingObject);
			if (ExistingDocument)
			{
				UGdReleaseA_ResetDocumentToDefaultState(ExistingDocument);
				ExistingDocument->Id = Document->Id;
				ExistingDocument->Name = Document->Name;
				ExistingDocument->PrimaryLanguage = Document->PrimaryLanguage;
				ExistingDocument->Languages = Document->Languages;
				ExistingDocument->Copyright = Document->Copyright;
				ExistingDocument->Version = Document->Version;
				ExistingDocument->Extensions = Document->Extensions;

				UGdReleaseA_TryDeleteDocument(Document);
				Document->MarkAsGarbage();
				Document = ExistingDocument;

				UGdReleaseA_MarkChildDocumentsForDeletion(ExistingDocument);
			}
			else if (ExistingObject)
			{
				UGdReleaseA_TryDeleteDocument(ExistingObject);
				UGdReleaseA_TryRenameDocument(Document, *NewName);
			}
			else
			{
				UGdReleaseA_TryRenameDocument(Document, *NewName);
			}
		}
		else if (PropertyName == TEXT("Name"))
		{
			if (Reader->IsNull())
			{
				UE_LOG(LogUGdReleaseA, Error, TEXT("Unexpected null value for property '%s' of document. Path: %s."), TEXT("ProjectSettings.Name"), *CombineGameDataPath(GameDataPath));
				return false;
			}
			bReadSuccess = Reader->ReadValue(Document->Name) && Reader->ReadNext();
			if (!bReadSuccess)
			{
				UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read value for property '%s' of document. Path: %s."), TEXT("ProjectSettings.Name"), *CombineGameDataPath(GameDataPath));
				return false;
			}
		}
		else if (PropertyName == TEXT("PrimaryLanguage"))
		{
			if (Reader->IsNull())
			{
				Reader->ReadNext();
				continue;
			}
			bReadSuccess = Reader->ReadValue(Document->PrimaryLanguage) && Reader->ReadNext();
			if (!bReadSuccess)
			{
				UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read value for property '%s' of document. Path: %s."), TEXT("ProjectSettings.PrimaryLanguage"), *CombineGameDataPath(GameDataPath));
				return false;
			}
		}
		else if (PropertyName == TEXT("Languages"))
		{
			if (Reader->IsNull())
			{
				Reader->ReadNext();
				continue;
			}
			bReadSuccess = Reader->ReadValue(Document->Languages) && Reader->ReadNext();
			if (!bReadSuccess)
			{
				UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read value for property '%s' of document. Path: %s."), TEXT("ProjectSettings.Languages"), *CombineGameDataPath(GameDataPath));
				return false;
			}
		}
		else if (PropertyName == TEXT("Copyright"))
		{
			if (Reader->IsNull())
			{
				Reader->ReadNext();
				continue;
			}
			bReadSuccess = Reader->ReadValue(Document->Copyright) && Reader->ReadNext();
			if (!bReadSuccess)
			{
				UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read value for property '%s' of document. Path: %s."), TEXT("ProjectSettings.Copyright"), *CombineGameDataPath(GameDataPath));
				return false;
			}
		}
		else if (PropertyName == TEXT("Version"))
		{
			if (Reader->IsNull())
			{
				UE_LOG(LogUGdReleaseA, Error, TEXT("Unexpected null value for property '%s' of document. Path: %s."), TEXT("ProjectSettings.Version"), *CombineGameDataPath(GameDataPath));
				return false;
			}
			bReadSuccess = Reader->ReadValue(Document->Version) && Reader->ReadNext();
			if (!bReadSuccess)
			{
				UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read value for property '%s' of document. Path: %s."), TEXT("ProjectSettings.Version"), *CombineGameDataPath(GameDataPath));
				return false;
			}
		}
		else if (PropertyName == TEXT("Extensions"))
		{
			if (Reader->IsNull())
			{
				Reader->ReadNext();
				continue;
			}
			bReadSuccess = Reader->ReadValue(Document->Extensions) && Reader->ReadNext();
			if (!bReadSuccess)
			{
				UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read value for property '%s' of document. Path: %s."), TEXT("ProjectSettings.Extensions"), *CombineGameDataPath(GameDataPath));
				return false;
			}
		}
		else
		{
			Reader->SkipAny();
		}
		GameDataPath.Pop();
	}
	Reader->ReadObjectEnd(NextToken);

	if (Reader->IsError())
	{
		UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
		return false;
	}


	UGdReleaseA_SweepMarkedChildDocuments(Document);

	return true;
}
template <typename IdType, typename DocumentType>
bool UGdReleaseA::ReadDocumentCollection
(
	const TSharedRef<IGameDataReader>& Reader,
	TMap<IdType,DocumentType*>& Collection,
	int32 Capacity,
	UObject* Outer,
	TArray<FString>& GameDataPath,
	bool NextToken
)
{
	Collection.Empty();
	if (Reader->IsNull())
	{
		return true;
	}

	const bool IsByIdCollection = Reader->GetNotation() == EJsonNotation::ObjectStart;
	auto Documents = TArray<DocumentType*>();

	if (Capacity > 0)
	{
		Documents.Reserve(Capacity);
	}

	if (IsByIdCollection)
	{
		Reader->ReadObjectBegin();
	}
	else
	{
		Reader->ReadArrayBegin();
	}

	int32 Count = -1;
	while (Reader->GetNotation() != EJsonNotation::ArrayEnd &&
			Reader->GetNotation() != EJsonNotation::ObjectEnd)
	{
		Count++;

		if (Reader->IsError())
		{
			UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
			return false;
		}
		if (Reader->IsNull())
		{
			Reader->ReadNext();
			continue;
		}

		auto DocumentId = Reader->GetIdentifier();
		if (!DocumentId.IsEmpty())
		{
			GameDataPath.Add(DocumentId);
		}
		else
		{
			GameDataPath.Add(FString::FromInt(Count));
		}

		DocumentType* Document = nullptr;
		if (ReadDocument(Reader, Document, Outer, GameDataPath) && Document != nullptr)
		{
			Documents.Add(Document);
		}
		else
		{
			UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read document. Path: %s."), *CombineGameDataPath(GameDataPath));
			return false;
		}

		GameDataPath.Pop();
	}
	if (IsByIdCollection)
	{
		Reader->ReadObjectEnd(NextToken);
	}
	else
	{
		Reader->ReadArrayEnd(NextToken);
	}

	if (Reader->IsError())
	{
		UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
		return false;
	}

	ToMapById(Collection, Documents);

	return true;
}
bool UGdReleaseA::ReadLocalizedText
(
	const TSharedRef<IGameDataReader>& Reader,
	FLocalizedText& LocalizedText,
	TArray<FString>& GameDataPath,
	bool NextToken
)
{
	auto LocStringMap = TMap<FString, FText>();
	Reader->ReadObjectBegin();
	while (Reader->GetNotation() != EJsonNotation::ObjectEnd)
	{
		if (Reader->IsError())
		{
			UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
			return false;
		}

		FString LanguageId = Reader->ReadMember();
		if (LanguageId == TEXT("notes")) {
			Reader->SkipAny();
			continue;
		}

		FText Text;
		GameDataPath.Add(LanguageId);
		if (!Reader->ReadValue(Text))
		{
			UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read localized text for language '%s'. Path: %s."), *LanguageId, *CombineGameDataPath(GameDataPath));
			return false;
		}
		Reader->ReadNext();
		GameDataPath.Pop();

		if (LanguageId.IsEmpty() || Text.IsEmpty())
		{
			continue;
		}
		LocStringMap.Add(LanguageId, Text);
	}
	Reader->ReadObjectEnd(NextToken);

	LocalizedText = FLocalizedText(LocStringMap, LanguageSwitcher);
	return true;
}

template <typename DocumentReferenceType>
bool UGdReleaseA::ReadDocumentReferenceCollection
(
	const TSharedRef<IGameDataReader>& Reader,
	TArray<DocumentReferenceType>& Collection,
	const FString& SchemaIdOrName,
	TArray<FString>& GameDataPath,
	bool NextToken
)
{
	Collection.Empty();
	if (Reader->IsNull())
	{
		return true;
	}

	const bool IsByIdCollection = Reader->GetNotation() == EJsonNotation::ObjectStart;

	if (IsByIdCollection)
	{
		Reader->ReadObjectBegin();
	}
	else
	{
		Reader->ReadArrayBegin();
	}
	while (Reader->GetNotation() != EJsonNotation::ArrayEnd &&
			Reader->GetNotation() != EJsonNotation::ObjectEnd)
	{
		if (Reader->IsError())
		{
			UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
			return false;
		}
		if (Reader->IsNull())
		{
			Reader->ReadNext();
			continue;
		}

		DocumentReferenceType DocumentReference;
		if (!ReadDocumentReference(Reader, DocumentReference, SchemaIdOrName, GameDataPath))
		{
			UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read document reference. Path: %s."), *CombineGameDataPath(GameDataPath));
			return false;
		}
		Collection.Add(DocumentReference);
	}
	if (IsByIdCollection)
	{
		Reader->ReadObjectEnd(NextToken);
	}
	else
	{
		Reader->ReadArrayEnd(NextToken);
	}

	if (Reader->IsError())
	{
		UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
		return false;
	}

	return true;
}

bool UGdReleaseA::ReadDocumentReference
(
	const TSharedRef<IGameDataReader>& Reader,
	FGameDataDocumentReference& DocumentReference,
	const FString& SchemaIdOrName,
	TArray<FString>& GameDataPath,
	bool NextToken
)
{
	FString Id;
	Reader->ReadObjectBegin();
	while (Reader->GetNotation() != EJsonNotation::ObjectEnd)
	{
		if (Reader->IsError())
		{
			UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
			return false;
		}

		auto MemberName = Reader->ReadMember();
		if (MemberName == TEXT("Id"))
		{
			if (!Reader->ReadValue(Id))
			{
				UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read 'Id' value for document reference. Path: %s."), *CombineGameDataPath(GameDataPath));
				return false;
			}
			Reader->ReadNext();
		}
		else
		{
			Reader->SkipAny();
		}
	}

	Reader->ReadObjectEnd(NextToken);

	if (Id.IsEmpty())
	{
		UE_LOG(LogUGdReleaseA, Error, TEXT("Document reference 'Id' is null or empty. Path: %s."), *CombineGameDataPath(GameDataPath));
		return false;
	}

	DocumentReference.Id = Id;
	DocumentReference.SchemaIdOrName = SchemaIdOrName;
	DocumentReference.GameData = this;

	return true;
}

template <typename FormulaType>
bool UGdReleaseA::ReadFormula
(
		const TSharedRef<IGameDataReader>& Reader,
		FormulaType*& Formula,
		UObject* Outer,
		TArray<FString>& GameDataPath,
		bool NextToken
)
{
	if (Reader->IsError())
	{
		UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
		return false;
	}

	TSharedPtr<FJsonObject> FormulaObject;
	if (!Reader->ReadObject(FormulaObject, NextToken) || FormulaObject == nullptr)
	{
		UE_LOG(LogUGdReleaseA, Error, TEXT("Failed to read JsonObject for Formula data type. Path: %s."), *CombineGameDataPath(GameDataPath));
		return false;
	}

	if (Reader->IsError())
	{
		UE_LOG(LogUGdReleaseA, Error, TEXT("File pasing failed due error '%s'. Path: %s."), *Reader->GetErrorMessage(), *CombineGameDataPath(GameDataPath));
		return false;
	}

	Formula = NewObject<FormulaType>(Outer);
	Formula->ExpressionTree.JsonObject = FormulaObject;
#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2
	UFormulaExpressionDefaultGlobal* GlobalObject = NewObject<UFormulaExpressionDefaultGlobal>(Outer, UFormulaExpressionDefaultGlobal::StaticClass(), NAME_None, EObjectFlags::RF_NoFlags);
	GlobalObject->This = Outer; // Document
	GlobalObject->GameData = this;
	Formula->Global = GlobalObject;
#endif

	return true;
}

FString UGdReleaseA::CombineGameDataPath(const TArray<FString>& GameDataPath)
{
	return FString::Join(GameDataPath, TEXT("/"));
}
TSharedPtr<FJsonObject> UGdReleaseA::MergeGameData(const TSharedPtr<FJsonObject>& GameDataDocument, const TSharedPtr<FJsonObject>& PatchDocument)
{
	const TSharedPtr<FJsonObject>* GameDataCollections;
	if (!GameDataDocument->TryGetObjectField(TEXT("Collections"), GameDataCollections)) {
		GameDataCollections = nullptr;
	}

	const TSharedPtr<FJsonObject>* PatchCollections;
	if (!PatchDocument->TryGetObjectField(TEXT("Collections"), PatchCollections)) {
		PatchCollections = nullptr;
	}

	auto MergedCollections = MakeShared<FJsonObject>();
	if (GameDataCollections != nullptr && GameDataCollections->IsValid() &&
		PatchCollections != nullptr && PatchCollections->IsValid())
	{
		auto& GameDataCollectionsMap = GameDataCollections->Get()->Values;
		auto& PatchCollectionsMap = PatchCollections->Get()->Values;

#if UE_VERSION_NEWER_THAN(5, 8, -1)
		TSet<UE::FSharedString> VisitedSchemas;
#else
		TSet<FString> VisitedSchemas;
#endif
		auto SchemaNames = MergeKeys(GameDataCollectionsMap, PatchCollectionsMap);

		for (auto SchemaName : SchemaNames.Get())
		{
			if (VisitedSchemas.Contains(SchemaName))
			{
				continue;
			}
			if (SchemaName == TEXT("55a4f32faca22e191098f3d9") || SchemaName == TEXT("ProjectSettings"))
			{
				VisitedSchemas.Add(TEXT("55a4f32faca22e191098f3d9"));
				VisitedSchemas.Add(TEXT("ProjectSettings"));

				auto GameDataDocumentCollection = GameDataCollectionsMap.Find(TEXT("55a4f32faca22e191098f3d9"));
				if (GameDataDocumentCollection == nullptr)
				{
					GameDataDocumentCollection = GameDataCollectionsMap.Find(TEXT("ProjectSettings"));
				}
				auto PatchDocumentCollection = PatchCollectionsMap.Find(TEXT("55a4f32faca22e191098f3d9"));
				if (PatchDocumentCollection == nullptr)
				{
					PatchDocumentCollection = PatchCollectionsMap.Find(TEXT("ProjectSettings"));
				}

				if (GameDataDocumentCollection != nullptr && PatchDocumentCollection != nullptr)
				{
					auto MergedCollection = MergeDocumentCollection<UGdReleaseAProjectSettings>(GameDataDocumentCollection->ToSharedRef(), PatchDocumentCollection->ToSharedRef(), false);
					MergedCollections->SetField(TEXT("ProjectSettings"), MergedCollection);
				}
				else if (GameDataDocumentCollection != nullptr)
				{
					MergedCollections->SetField(TEXT("ProjectSettings"), *GameDataDocumentCollection);
				}
				else if (PatchDocumentCollection != nullptr)
				{
					MergedCollections->SetField(TEXT("ProjectSettings"), *PatchDocumentCollection);
				}
			}
			else
			{
				/* ignore schema */
			}
		}
	}
	else if (GameDataCollections != nullptr && GameDataCollections->IsValid())
	{
		MergedCollections = GameDataCollections->ToSharedRef();
	}
	else if (PatchCollections != nullptr && PatchCollections->IsValid())
	{
		MergedCollections = PatchCollections->ToSharedRef();
	}

	int MergedChangeNumber;
	if (GameDataDocument->HasTypedField<EJson::Number>(TEXT("ChangeNumber")))
	{
		GameDataDocument->GetField<EJson::Number>(TEXT("ChangeNumber"))->TryGetNumber(MergedChangeNumber);
	}
	if (PatchDocument->HasTypedField<EJson::Number>(TEXT("ChangeNumber")))
	{
		PatchDocument->GetField<EJson::Number>(TEXT("ChangeNumber"))->TryGetNumber(MergedChangeNumber);
	}

	FString MergedRevisionHash;
	if (GameDataDocument->HasTypedField<EJson::String>(TEXT("RevisionHash")))
	{
		GameDataDocument->GetField<EJson::String>(TEXT("RevisionHash"))->TryGetString(MergedRevisionHash);
	}
	if (PatchDocument->HasTypedField<EJson::String>(TEXT("RevisionHash")))
	{
		PatchDocument->GetField<EJson::String>(TEXT("RevisionHash"))->TryGetString(MergedRevisionHash);
	}

	auto MergedGameData = MakeShared<FJsonObject>();
	MergedGameData->SetField(TEXT("ChangeNumber"), MakeShared<FJsonValueNumber>(MergedChangeNumber));
	MergedGameData->SetField(TEXT("RevisionHash"), MakeShared<FJsonValueString>(MergedRevisionHash));
	MergedGameData->SetField(TEXT("Collections"), MakeShared<FJsonValueObject>(MergedCollections));
	return MergedGameData;
}

struct UGdReleaseA_ToIdMapper
{
	static TSharedPtr<FJsonObject> ToDocumentById(TSharedRef<FJsonValue> Collection)
	{
		TSharedPtr<FJsonObject>* CollectionByIdPtr;
		TArray<TSharedPtr<FJsonValue>>* CollectionPtr;
		if (Collection->TryGetObject(CollectionByIdPtr) && CollectionByIdPtr != nullptr && CollectionByIdPtr->IsValid())
		{
			return *CollectionByIdPtr;
		}
		else if (Collection->TryGetArray(CollectionPtr) && CollectionPtr != nullptr)
		{
			auto CollectionById = MakeShared<FJsonObject>();
			for (auto DocumentOrNullPtr : *CollectionPtr)
			{
				TSharedPtr<FJsonObject>* DocumentObjectPtr;
				if (DocumentOrNullPtr->TryGetObject(DocumentObjectPtr) && DocumentObjectPtr->IsValid())
				{
					auto Document = DocumentObjectPtr->ToSharedRef();
					auto IdValue = Document->TryGetField(TEXT("Id"));
					double IdValueDouble;
					FString IdValueString;
					bool IdValueBool;
					if (IdValue != nullptr && IdValue->TryGetNumber(IdValueDouble))
					{
						CollectionById->SetObjectField(FString::Format(TEXT("{0}"), {IdValueDouble}), Document);
					}
					else if (IdValue != nullptr && IdValue->TryGetString(IdValueString))
					{
						CollectionById->SetObjectField(IdValueString, Document);
					}
					else if (IdValue != nullptr && IdValue->TryGetBool(IdValueBool))
					{
						CollectionById->SetObjectField(IdValueBool ? TEXT("True") : TEXT("False"), Document);
					}
				}
			}
			return CollectionById;
		}
		else
		{
			return MakeShared<FJsonObject>();
		}
	}
};

template <typename DocumentType>
TSharedPtr<FJsonValue> UGdReleaseA::MergeDocumentCollection(TSharedRef<FJsonValue> OriginalCollection, TSharedRef<FJsonValue> ModifiedCollection, bool PurgeRest)
{
	auto OriginalCollectionById = UGdReleaseA_ToIdMapper::ToDocumentById(OriginalCollection);
	auto ModifiedCollectionById = UGdReleaseA_ToIdMapper::ToDocumentById(ModifiedCollection);
	auto MergedCollectionById = MakeShared<FJsonObject>();
	auto DocumentIds = PurgeRest ? MergeKeys(ModifiedCollectionById->Values, {}) : MergeKeys(OriginalCollectionById->Values, ModifiedCollectionById->Values);

	for (auto DocumentId : DocumentIds.Get())
	{
		TSharedPtr<FJsonValue> OriginalDocumentObjectPtr = OriginalCollectionById->TryGetField(DocumentId);
		auto OriginalDocumentExists = OriginalDocumentObjectPtr.IsValid();

		TSharedPtr<FJsonValue> ModifiedDocumentObjectPtr = ModifiedCollectionById->TryGetField(DocumentId);
		auto ModifiedDocumentExists = ModifiedDocumentObjectPtr.IsValid();

		TSharedPtr<FJsonValue> MergedDocument = nullptr;
		if (OriginalDocumentExists && !ModifiedDocumentExists)
		{
			// unchanged
			MergedDocument = OriginalDocumentObjectPtr;
		}
		else if (OriginalDocumentExists && OriginalCollectionById->HasTypedField<EJson::Null>(DocumentId))
		{
			// keep deleted documents as deleted
			MergedDocument = nullptr;
		}
		else if (!OriginalDocumentExists && ModifiedDocumentExists)
		{
			// modified
			MergedDocument = ModifiedDocumentObjectPtr;
		}
		else if (OriginalDocumentExists && OriginalCollectionById->HasTypedField<EJson::Object>(DocumentId) &&
			ModifiedDocumentExists && ModifiedCollectionById->HasTypedField<EJson::Object>(DocumentId))
		{
			// merged
			MergedDocument = MergeDocument<DocumentType>(OriginalDocumentObjectPtr.ToSharedRef(), ModifiedDocumentObjectPtr.ToSharedRef());
		}
		else
		{
			// modified
			MergedDocument = ModifiedDocumentObjectPtr;
		}


		if (MergedDocument)
		{
			MergedCollectionById->SetField(DocumentId, MergedDocument);
		}
		else
		{
			MergedCollectionById->SetField(DocumentId, MakeShared<FJsonValueNull>());
		}
	}

	return MakeShared<FJsonValueObject>(MergedCollectionById);
}

template <typename DocumentType>
TSharedPtr<FJsonValue> UGdReleaseA::MergeDocument(TSharedRef<FJsonValue> OriginalDocument, TSharedRef<FJsonValue> ModifiedDocument)
{
	TSharedPtr<FJsonObject>* OriginalDocumentObjectPtr;
	if (!OriginalDocument->TryGetObject(OriginalDocumentObjectPtr))
	{
		OriginalDocumentObjectPtr = nullptr;
	}

	TSharedPtr<FJsonObject>* ModifiedDocumentObjectPtr;
	if (!ModifiedDocument->TryGetObject(ModifiedDocumentObjectPtr))
	{
		ModifiedDocumentObjectPtr = nullptr;
	}

	if (OriginalDocumentObjectPtr == nullptr || !OriginalDocumentObjectPtr->IsValid() ||
		ModifiedDocumentObjectPtr == nullptr || !ModifiedDocumentObjectPtr->IsValid())
	{
		return nullptr;
	}

	auto ModifiedDocumentObjectRef = ModifiedDocumentObjectPtr->ToSharedRef();
	auto OriginalDocumentObjectRef = OriginalDocumentObjectPtr->ToSharedRef();
	auto MergedDocument = MakeShared<FJsonObject>();
	if constexpr (std::is_same_v<DocumentType, UGdReleaseAProjectSettings>)
	{
		MergePropertyValue(MergedDocument, OriginalDocumentObjectRef, ModifiedDocumentObjectRef, TEXT("Id"));
		MergePropertyValue(MergedDocument, OriginalDocumentObjectRef, ModifiedDocumentObjectRef, TEXT("Name"));
		MergePropertyValue(MergedDocument, OriginalDocumentObjectRef, ModifiedDocumentObjectRef, TEXT("PrimaryLanguage"));
		MergePropertyLanguagesValue(MergedDocument, OriginalDocumentObjectRef, ModifiedDocumentObjectRef, TEXT("Languages"));
		MergePropertyValue(MergedDocument, OriginalDocumentObjectRef, ModifiedDocumentObjectRef, TEXT("Copyright"));
		MergePropertyValue(MergedDocument, OriginalDocumentObjectRef, ModifiedDocumentObjectRef, TEXT("Version"));
		MergePropertyValue(MergedDocument, OriginalDocumentObjectRef, ModifiedDocumentObjectRef, TEXT("Extensions"));
	}
	else
	{
		/* ignore type */
	}

	return MakeShared<FJsonValueObject>(MergedDocument);
}


void UGdReleaseA::MergePropertyDocumentValue(TSharedRef<FJsonObject> MergedDocument, TSharedRef<FJsonObject> OriginalDocument, TSharedRef<FJsonObject> ModifiedDocument, const FString PropertyName, OptionalMergeValueFunc MergeFn)
{
	const TSharedPtr<FJsonObject>* ModifiedDocumentObjectPtr;
	if (ModifiedDocument->TryGetObjectField(PropertyName, ModifiedDocumentObjectPtr) &&
		ModifiedDocumentObjectPtr != nullptr && ModifiedDocumentObjectPtr->IsValid() &&
		!ModifiedDocumentObjectPtr->Get()->HasField(TEXT("Id")) &&
		OriginalDocument->HasTypedField<EJson::Null>(PropertyName))
	{
		// unable to merge partial data into missing document
		MergedDocument->SetField(PropertyName, MakeShared<FJsonValueNull>());
		return;
	}

	MergePropertyValue(MergedDocument, OriginalDocument, ModifiedDocument, PropertyName, MergeFn);
}

void UGdReleaseA::MergePropertyLanguagesValue(TSharedRef<FJsonObject> MergedDocument, TSharedRef<FJsonObject> OriginalDocument, TSharedRef<FJsonObject> ModifiedDocument, const FString PropertyName)
{
	auto OriginalValue = OriginalDocument->TryGetField(PropertyName);
	auto OriginalValueExists = OriginalValue.IsValid();

	auto ModifiedValue = ModifiedDocument->TryGetField(PropertyName);
	auto ModifiedValueExists = ModifiedValue.IsValid();

	if (!OriginalValueExists && !ModifiedValueExists)
	{
		return;
	}

	auto OriginalLanguageListStr = OriginalValueExists && OriginalValue->Type == EJson::String ? OriginalValue->AsString() : FString();
	auto ModifiedLanguageListStr = ModifiedValueExists && ModifiedValue->Type == EJson::String ? ModifiedValue->AsString() : FString();
	auto OriginalLanguageList = TArray<FString>();
	auto ModifiedLanguageList = TArray<FString>();

	ParseLanguageList(OriginalLanguageListStr, OriginalLanguageList);
	ParseLanguageList(ModifiedLanguageListStr, ModifiedLanguageList);

	for (const auto LanguageId : ModifiedLanguageList)
	{
		if (OriginalLanguageList.Contains(LanguageId))
		{
			continue;
		}
		OriginalLanguageList.Add(LanguageId);
	}

	MergedDocument->SetStringField(PropertyName, FString::Join(OriginalLanguageList, TEXT(";")));
}

void UGdReleaseA::MergePropertyValue(TSharedRef<FJsonObject> MergedDocument, TSharedRef<FJsonObject> OriginalDocument, TSharedRef<FJsonObject> ModifiedDocument, const FString PropertyName, OptionalMergeValueFunc MergeFn)
{
	auto OriginalValue = OriginalDocument->TryGetField(PropertyName);
	auto OriginalValueExists = OriginalValue.IsValid();

	auto ModifiedValue = ModifiedDocument->TryGetField(PropertyName);
	auto ModifiedValueExists = ModifiedValue.IsValid();

	if (!OriginalValueExists && !ModifiedValueExists)
	{
		return;
	}

	TSharedPtr<FJsonValue> MergedValue = nullptr;
	if (OriginalValueExists && !ModifiedValueExists)
	{
		// unchanged
		MergedValue = OriginalValue;
	}
	else if (!OriginalValueExists && ModifiedValueExists)
	{
		// modified
		MergedValue = ModifiedValue;
	}
	else if (OriginalValue != nullptr && ModifiedValue != nullptr)
	{
		// modified
		if (MergeFn.IsSet())
		{
			MergedValue = MergeFn.GetValue()(OriginalValue.ToSharedRef(), ModifiedValue.ToSharedRef());
		}
		else
		{
			MergedValue = ModifiedValue;
		}
	}
	else
	{
		// modified
		MergedValue = ModifiedValue;
	}


	if (MergedValue != nullptr)
	{
		MergedDocument->SetField(PropertyName, MergedValue);
	}
	else
	{
		MergedDocument->SetField(PropertyName, MakeShared<FJsonValueNull>());
	}
}

TSharedRef<FJsonValue> UGdReleaseA::MergeLocalizedText(TSharedRef<FJsonValue> OriginalLocalizedText, TSharedRef<FJsonValue> ModifiedLocalizedText)
{
	struct TextComparer
	{
		static bool IsSame(TSharedRef<FJsonObject> Left, TSharedRef<FJsonObject> Right)
		{
#if UE_VERSION_NEWER_THAN(5, 8, -1)
			TArray<UE::FSharedString> Keys;
#else
			TArray<FString> Keys;
#endif
			for(int i = 0; i < 2; i++)
			{
				if (i == 0)
				{
					Left->Values.GetKeys(Keys);
				}
				else
				{
					Right->Values.GetKeys(Keys);
				}

				for (auto LanguageId : Keys)
				{
					if (LanguageId == TEXT("notes") )
					{
						continue;
					}

					auto LeftValue = Left->TryGetField(LanguageId);
					auto RightValue = Right->TryGetField(LanguageId);
					FString LeftText, RightText;

					if (LeftValue == nullptr || RightValue == nullptr || LeftValue->Type != RightValue->Type)
					{
						return false;
					}

					if (LeftValue->TryGetString(LeftText) &&
						RightValue->TryGetString(RightText) &&
						LeftText != RightText)
					{
						return false;
					}

				}
			}

			return true;
		}
	};

	TSharedPtr<FJsonObject>* OriginalLocalizedTextPtr;
	if (!OriginalLocalizedText->TryGetObject(OriginalLocalizedTextPtr))
	{
		OriginalLocalizedTextPtr = nullptr;
	}

	TSharedPtr<FJsonObject>* ModifiedLocalizedTextPtr;
	if (!ModifiedLocalizedText->TryGetObject(ModifiedLocalizedTextPtr))
	{
		ModifiedLocalizedTextPtr = nullptr;
	}

	if (OriginalLocalizedTextPtr == nullptr || !OriginalLocalizedTextPtr->IsValid())
	{
		return ModifiedLocalizedTextPtr != nullptr && ModifiedLocalizedTextPtr->IsValid() ?
			MakeShared<FJsonValueObject>(*ModifiedLocalizedTextPtr) : static_cast<TSharedRef<FJsonValue>>(MakeShared<FJsonValueNull>());
	}
	else if (ModifiedLocalizedTextPtr == nullptr || !ModifiedLocalizedTextPtr->IsValid())
	{
		return OriginalLocalizedTextPtr != nullptr && OriginalLocalizedTextPtr->IsValid() ?
			MakeShared<FJsonValueObject>(*OriginalLocalizedTextPtr) : static_cast<TSharedRef<FJsonValue>>(MakeShared<FJsonValueNull>());
	}
	else if (TextComparer::IsSame(OriginalLocalizedTextPtr->ToSharedRef(), ModifiedLocalizedTextPtr->ToSharedRef()))
	{
		return MakeShared<FJsonValueObject>(*OriginalLocalizedTextPtr);
	}

	auto& OriginalLocalizedTextMap = OriginalLocalizedTextPtr->Get()->Values;
	auto& ModifiedLocalizedTextMap = ModifiedLocalizedTextPtr->Get()->Values;
	auto LanguageIds = MergeKeys(OriginalLocalizedTextMap, ModifiedLocalizedTextMap);
	auto MergedLocalizedText = MakeShared<FJsonObject>();
	for (auto LanguageId : LanguageIds.Get())
	{
		auto OriginalText = OriginalLocalizedTextMap.Find(LanguageId);
		auto ModifiedText = ModifiedLocalizedTextMap.Find(LanguageId);

		if (ModifiedText != nullptr && ModifiedText->IsValid())
		{
			MergedLocalizedText->SetField(LanguageId, *ModifiedText);
		}
		else if (OriginalText != nullptr && OriginalText->IsValid())
		{
			MergedLocalizedText->SetField(LanguageId, *OriginalText);
		}
	}

	return MakeShared<FJsonValueObject>(MergedLocalizedText);
}

template <typename KeyType>
TSharedRef<TArray<KeyType>> UGdReleaseA::MergeKeys(const TMap<KeyType, TSharedPtr<FJsonValue>>& Collection1, const TMap<KeyType, TSharedPtr<FJsonValue>>& Collection2)
{
	TArray<KeyType> Keys;
	Collection1.GetKeys(Keys);

	auto MergedKeys = MakeShared<TArray<KeyType>>();
	for (auto Key : Keys)
	{
		MergedKeys->Push(Key);
	}

	Collection2.GetKeys(Keys);
	for (auto Key : Keys)
	{
		if (MergedKeys->Contains(Key))
		{
			continue; // skip duplicates
		}
		MergedKeys->Push(Key);
	}
	return MergedKeys;
}
void UGdReleaseA::ApplyVisitor(FVisitor& Visitor) const
{
	for (const auto Document : GetRootDocuments())
	{
		Visitor.Visit(Document);
	}
}

void UGdReleaseA::ResolveAllReferences()
{
	auto DereferencingVisitor = UGdReleaseA::FDereferencingVisitor();
	ApplyVisitor(DereferencingVisitor);
}

void UGdReleaseA::FindAllDocuments()
{
	auto FindingVisitor = UGdReleaseA::FFindingVisitor();
	ApplyVisitor(FindingVisitor);


	ToMapById(this->AllProjectSettingsList, FindingVisitor.ProjectSettings);
}

void UGdReleaseA::FVisitor::Visit(UGameDataDocument* Document)
{
	if (Document == nullptr)
	{
		return;
	}
	else if ((Document->GetClass() == UGdReleaseAProjectSettings::StaticClass()))
	{
		Visit(static_cast<UGdReleaseAProjectSettings&>(*Document));
	}
}
void UGdReleaseA::FVisitor::Visit(UGdReleaseAProjectSettings& Document)
{
}
void UGdReleaseA::FFindingVisitor::Visit(UGdReleaseAProjectSettings& Document)
{
	if (this->ProjectSettings.Num() == 0)
	{
		this->ProjectSettings.Reserve(6);
	}
	this->ProjectSettings.Add(&Document);

	FVisitor::Visit(Document);
}
void UGdReleaseA::FDereferencingVisitor::Visit(UGdReleaseAProjectSettings& Document)
{
	FVisitor::Visit(Document);
}
void UGdReleaseA::FLanguagesUpdateVisitor::Visit(UGdReleaseAProjectSettings& Document)
{
	FVisitor::Visit(Document);
}
UGdReleaseA::FLanguagesUpdateVisitor::FLanguagesUpdateVisitor(const TArray<FString>& LanguageIds)
	: LanguageIds(LanguageIds)
{
}
void UGdReleaseA::FLanguagesUpdateVisitor::RemoveExtraKeys(TMap<FString, FText>& TextByLanguageId)
{
	for (auto It = TextByLanguageId.CreateIterator(); It; ++It)
	{
		if (!this->LanguageIds.Contains(It->Key))
		{
			It.RemoveCurrent();
		}
	}
}
